Update README.rst - use HTTPS URL instead of SSH
Using the instructed `pip install git+ssh://git@github.com:aws-samples/aws-iamctl.git` generated 
```
Collecting git+ssh://****@github.com:aws-samples/aws-iamctl.git
  Cloning ssh://****@github.com:aws-samples/aws-iamctl.git to /private/var/folders/_r/sdqm1b615ml91n6zkdxxv1tc0000gp/T/pip-req-build-yad72clz
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com:aws-samples/aws-iamctl.git' /private/var/folders/_r/sdqm1b615ml91n6zkdxxv1tc0000gp/T/pip-req-build-yad72clz Check the logs for full command output.
```
Using the HTTPS URL provided by Github instead worked.